### ISSUE TITLE
Pervasive use of non-type-safe primitives in coqchk

### ISSUE THREAD

**Issue by whitequark** [rocq-prover/rocq#7839]
I had an idea that would involve cross-compilation of `coqchk` and feeding it untrusted input, so I decided to see if that can be done. I was quite surprised to see 137 instances of `Obj.*` in TCB, 40 instances of the "%identity" primitive under a different name, 51 instance of `Array.unsafe_*`, 9 instances of `String.unsafe_*`, and especially the `values.ml` and `validate.ml` files from coqchk. 

Needless to say, I have no confidence at all that coqchk will do its job on potentially malicious input. This is not at all what I expect from a proof checker.

To add to this, the use of Obj ties Coq to a specific version of a specific implementation of the OCaml runtime, which I can't imagine is desirable.

To add more to this, the use of OCaml marshaling for `vo` files makes it significantly harder than necessary to implement a hypothetical `safecoqchk` that would not suffer from any of these issues.

I understand that my first major interaction with the Coq community being a complaint does not look good, but I hope it's clear that I only wish Coq be the best it can be. In any case, I'll be glad to fix some of these once there's consensus on what should be done.

I would really like to see Coq:
  - [ ] use a proper serialization format for `vo` files;
  - [x] remove `Hashcons.Hobj` entirely, it is not used anywhere in Coq (#7840);
  - [x] remove `CEphemeron`, which is only necessary because of the use of marshalling, or in any case, use GADTs and standard library ephemerons instead (#7850);
  - [ ] use GADTs for implementing `Store`, since there's `option` overhead anyway;
  - [ ] ~use [inline records](https://blog.janestreet.com/ocaml-4-03-everything-else/) for implementing `CList` since that allows doing the obvious thing in a type-safe way~ wouldn't work because CList.list has to be compatible with Prelude.list;
  - [ ] ~rely on flambda to optimize the type-safe but more naive implementations of select primitives in `CMap`, `CSet` and `Int` that currently use `Obj.magic` to expose the standard library internals~ flambda cannot do this;
  - [x] use either a proper custom block in `Canary`, or at least transmute a closure without making any particular assumptions about its layout, or remove it (#7841);
  - [ ] use the new Spacetime profiler instead of `CObj` or at least not make `CObj` a hard requirement for `coqchk`;
  - [ ] make the use of unsafe Array/String primitives optional with a switch;
  - [x] don't use `Obj.truncate` in `Hashset` because it is [probably going to be deprecated and unsafe](https://github.com/ocaml/ocaml/pull/1725#issue-181811171) (#11262)

This will address every use of non-type-safe primitives in TCB.

**Comment by whitequark** [comment]
As an aside, to determine the approximation of TCB with module granularity, I extracted `coqchk` from the Coq source and measured its size, which is ~22 kloc total. This is both smaller than what I've been told (~30 kloc), and over a half of it is in `clib`, which has many parts not essential to proof checking. I would hope that eventually, the core of `coqchk` could be a function that is pure other than for allocation, mutation and exceptions.
```
SLOC    Directory       SLOC-by-Language (Sorted)
11660   clib            ml=11660
7716    checker         ml=7716
1943    lib             ml=1943
987     kernel          ml=987
```

**Comment by Blaisorblade** [comment]
Without understanding the details, https://github.com/coq/coq/pull/6266#issuecomment-348201175 seems a (recent?) assessment of the situation.

**Comment by SkySkimmer** [comment]
> don't use Obj.truncate in Hashset because it is probably going to be deprecated and unsafe; this is the only one for which I don't see a migration path.

That part of the code is copied from https://github.com/ocaml/ocaml/blob/baaaecab6b0fb030bc4995f8ab0b065accfd5ea7/stdlib/weak.ml#L169 so if they end up removing `truncate` we can just do whatever they do.

**Comment by whitequark** [comment]
> Maybe we should just drop the canary.

https://github.com/coq/coq/pull/7841

**Comment by ppedrot** [comment]
@whitequark Also, I believe that many portions of the unsafe code you are mentioning exists in the modules `coqchk` uses, but is not used by it in practice. It's dead code in the binary.

The use of OCaml marshalling format is a completely different story indeed, and as you remark having an OCaml implementation + a posteriori checking makes us heavily tied to the OCaml runtime. Unluckily, I do not know how to perform it at the same level of efficiency or without losing sharing, which are both critical performancewise.

**Comment by anton-trunov** [comment]
> there are some other interesting projects trying to develop a checker using Rust and a certified Gallina execution engine
@ejgallego Could you point me to some of those projects?

**Comment by mattam82** [comment]
Very interesting assessment indeed! The marshaling issue is somewhat complicated indeed. I wondered many times if we could not benefit of the techniques used in why3/frama-C where they seem to achieve type-safe and perfectly sharing marshaling but @ppedrot tells me it’s difficult given that we can put anything inside .vos because of libobject déclarations being stored there. I believe most should be for non-logical stuff the checker doesn’t have to check though so maybe a limited safe marchalling just for kernel declarations could be doable?
@ejgallego refers to a project by @ppedrot to write a checker in Rust and another one part of the Template Coq project whose purpose is to verify the typing/conversion algorithms (idealized purely functional versions for now) in Coq.

**Comment by whitequark** [comment]
> The marshaling issue is somewhat complicated indeed. I wondered many times if we could not benefit of the techniques used in why3/frama-C where they seem to achieve type-safe and perfectly sharing marshaling but @ppedrot tells me it’s difficult given that we can put anything inside .vos because of libobject déclarations being stored there. I believe most should be for non-logical stuff the checker doesn’t have to check though so maybe a limited safe marchalling just for kernel declarations could be doable?

A possible alternative would be to use a ppx rewriter to generate unmarshalling functions such that the same on-disk format can be used, but the checker would not use anything from `Obj` to load it, similar to what the Rust implementation does but more automated.

**Comment by whitequark** [comment]
@ejgallego 

> I will try to provide some more feedback once I get a free minute, just let me indeed remark that Coq, as it stands today, it is just not designed to be adversary resistant. IMVHO making the checker robust would amount to almost a rewriting, and there are some other interesting projects trying to develop a checker using Rust and a certified Gallina execution engine

I would like to say that making coqchk reasonably adversary resistant (in other words, memory-safe) has a lot of value.

First, coqchk is tried and proven, whereas these rewrite projects will take a lot of time to get to the same level of compatibility.

Second, coqchk can be compiled to OCaml bytecode, which runs on a very simple VM and can be easily cross-compiled, such as with js_of_ocaml, or my LLVM OCaml backend project (worked but was slower than ocamlopt due to GC issues, so I shelved it). Conversely, Rust has a complicated runtime model, it can only realistically target whatever LLVM targets (there is an effort underway to fix that, but it isn't going to change any time soon).

**Comment by whitequark** [comment]
> rely on flambda to optimize the type-safe but more naive implementations of select primitives in `CMap`, `CSet` and `Int` that currently use `Obj.magic` to expose the standard library internals

I checked and flambda does not appear to be able to inline functions from stdlib functors. Aw.

**Comment by whitequark** [comment]
@maximedenes How would you feel about a patchset whose goal would be to minimize the amount of dependencies coqchk has on the rest of the codebase? Perhaps splitting it into a "coqchk/pure" which would have an entry point <code>val check : proof -> [`Ok | `Error of message list]</code>, and "coqchk/frontend", which would read files, output text on the terminal, and so on.

**Comment by maximedenes** [comment]
> How would you feel about a patchset whose goal would be to minimize the amount of dependencies coqchk has on the rest of the codebase? Perhaps splitting it into a "coqchk/pure" which would have an entry point val check : proof -> [`Ok | `Error of message list], and "coqchk/frontend", which would read files, output text on the terminal, and so on.

If it doesn't introduce code duplication, I think it would be a nice idea.

**Comment by DemiMarie** [comment]
> > rely on flambda to optimize the type-safe but more naive implementations of select primitives in `CMap`, `CSet` and `Int` that currently use `Obj.magic` to expose the standard library internals
> 
> I checked and flambda does not appear to be able to inline functions from stdlib functors. Aw.

It can with an annotation: https://github.com/ocaml-flambda/flambda-backend/issues/963#issuecomment-1312559951
